# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-18 01:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0003_auto_20170817_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='url',
            field=models.CharField(default='abc', max_length=50),
            preserve_default=False,
        ),
    ]
