# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-18 03:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0004_menuitem_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='url',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='explicit_url',
            field=models.URLField(default='asdasd'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menuitem',
            name='named_url',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
