# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-18 04:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0005_auto_20170818_0654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='explicit_url',
            field=models.URLField(blank=True),
        ),
    ]
