# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-18 08:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0007_auto_20170818_0726'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='slug',
        ),
    ]
